## Analytic 30 Code

#### OPIM5770 | Fall 2018 | Team 4

###### This notebook contains code to generate file necessary for input to analytic 30 at a transaction level. Designed by Team 4.

In [1]:
# Import required modules
import pandas as pd
import numpy as np
import os

In [3]:
# Load the BSAK_BKPF (Note: with date parsing enabled, may take some time to complete)
parse_dates = [ 'Document_Date_in_Document'
               ,'Clearing_Date'
               ,'Day_On_Which_Accounting_Document_Was_Entered']

BSAK_BKPF_DF = pd.read_csv(r'./../../src/BSAK_BKPF.csv' 
                           , sep="|"
                           , quotechar="'"
                           , low_memory=False
                           , encoding='latin1'
                           , usecols = [ 
                                     'Company_Code',
                                     'Account_Number_of_Vendor_or_Creditor',
                                     'Reference_Document_Number',
                                     'Accounting_Document_Number',
                                     'Document_Type',
                                     'Number_of_Line_Item_Within_Accounting_Document',
                                     'Document_Number_of_the_Clearing_Document',
                                     'Reference_Document_Number',
                                     'Fiscal_Year',
                                     'Document_Date_in_Document',
                                     'Clearing_Date',
                                     'Day_On_Which_Accounting_Document_Was_Entered',
                                     'Debit_Credit_Indicator',
                                     'Currency_Key',
                                     'Amount_in_Document_Currency',
                                     'Amount_in_Local_Currency',
                                     'Reverse_Document_Number',
                                     'Terms_of_Payment_Key'
                                     ]
                           , dtype = { 
                                     'Company_Code': str,
                                     'Account_Number_of_Vendor_or_Creditor': str,
                                     'Reference_Document_Number': str,
                                     'Accounting_Document_Number': str,
                                     'Document_Type': str, 
                                     'Number_of_Line_Item_Within_Accounting_Document':int,
                                     'Document_Number_of_the_Clearing_Document': str,
                                     'Reference_Document_Number':str,
                                     'Fiscal_Year':int,
                                     'Document_Date_in_Document':str, # REQUIRES DATE PARSING
                                     'Clearing_Date': str, # REQUIRES DATE PARSING
                                     'Day_On_Which_Accounting_Document_Was_Entered': str, #REQUIRES DATE PARSING
                                     'Debit_Credit_Indicator': str,
                                     'Currency_Key':str,
                                     'Amount_in_Document_Currency': float,
                                     'Amount_in_Local_Currency':float,
                                     'Reverse_Document_Number':str,
                                     'Terms_of_Payment_Key':str
                                   }
                          , parse_dates=parse_dates)

BSAK_BKPF_DF.rename(columns=
          {
              'Company_Code': 'COMPANY_CODE',
              'Account_Number_of_Vendor_or_Creditor': 'VENDOR_ID',
              'Reference_Document_Number': 'VENDOR_INVOICE_NUMBER',
              'Accounting_Document_Number': 'ACCOUNTING_DOC_NUM',
              'Document_Type': 'DOCUMENT_TYPE',
              'Number_of_Line_Item_Within_Accounting_Document':'LINE_ITEM_ACCT_DOC_NUM',
              'Document_Number_of_the_Clearing_Document':'CLEARING_DOC_NUM',
              'Reference_Document_Number': 'REFERENCE_DOC_NBR',
              'Fiscal_Year': 'FISCAL_YEAR',
              'Document_Date_in_Document': 'DOCUMENT_DATE',
              'Clearing_Date': 'CLEARING_DATE',
              'Day_On_Which_Accounting_Document_Was_Entered': 'DAY_DOC_ENTERED',
              'Debit_Credit_Indicator': 'DR_CR_INDICATOR',
              'Currency_Key': 'DOC_CURRENCY_INDICATOR',
              'Amount_in_Document_Currency': 'INVOICE_                    AMT_DOC_CURRENCY',
              'Amount_in_Local_Currency': 'INVOICE_AMT_REPORT_CURRENCY',
              'Reverse_Document_Number': 'REVERSE_DOC_NBR',
              'Terms_of_Payment_Key':'VENDOR_PAYMENT_TERM'
          }, inplace=True)

In [36]:
# Filter out unnecessary data types
BSAK_BKPF_DF = BSAK_BKPF_DF[BSAK_BKPF_DF['DOCUMENT_TYPE'] != 'ZP']
BSAK_BKPF_DF = BSAK_BKPF_DF[BSAK_BKPF_DF['DOCUMENT_TYPE'] != 'KZ']

In [47]:
# Open the T052 dataset to dataframe
T052=pd.read_csv(r'./../../src/T052_AltColTitles.csv',encoding='Latin1')

# Rename the columns to match nomenclature
T052.rename(columns={
    'Terms_of_Payment_Key':'VENDOR_PAYMENT_TERM_KEY',
    'Days_from_Baseline_Date_for_Payment':'PAYMENT_TERM'
    }, inplace=True)

# Group by to remove duplicate payment terms - take largest to be conservative
T052 = T052[['VENDOR_PAYMENT_TERM_KEY','PAYMENT_TERM']]
T052 = T052.groupby('VENDOR_PAYMENT_TERM_KEY', as_index=False)['PAYMENT_TERM'].max()

In [57]:
# Join to get the payment terms
joinDF = pd.merge(
                  left=BSAK_BKPF_DF
                  , right=T052
                  , left_on = 'VENDOR_PAYMENT_TERM'
                  , right_on = 'VENDOR_PAYMENT_TERM_KEY'
                  , how='left')

In [50]:
joinDF.head()

,COMPANY_CODE,VENDOR_ID,CLEARING_DATE,CLEARING_DOC_NUM,FISCAL_YEAR,ACCOUNTING_DOC_NUM,LINE_ITEM_ACCT_DOC_NUM,DOCUMENT_DATE,DAY_DOC_ENTERED,DOC_CURRENCY_INDICATOR,REFERENCE_DOC_NBR,DOCUMENT_TYPE,DR_CR_INDICATOR,INVOICE_AMT_REPORT_CURRENCY,INVOICE_ AMT_DOC_CURRENCY,VENDOR_PAYMENT_TERM,REVERSE_DOC_NBR,VENDOR_PAYMENT_TERM_KEY,PAYMENT_TERM
0,1001,0000020660,2018-02-17,2900443156,2018,1900009335,1,2018-01-31,2018-02-16,USD,013118CDV,KR,H,15826.25,15826.25,0005,NaN,0005,10.0
1,1001,0000020660,2018-04-04,2900453409,2018,1900019966,1,2018-03-04,2018-04-03,USD,040318TRAV,KR,H,30904.38,30904.38,0005,NaN,0005,10.0
2,1001,0000020660,2018-03-10,2900447675,2018,1900012919,1,2018-02-28,2018-03-05,USD,022818CDV,KR,H,20920.00,20920.00,0005,NaN,0005,10.0
3,1001,0000020660,2018-05-22,2900463376,2018,1900029522,1,2018-05-18,2018-05-21,USD,051818TRAV,KR,H,36450.77,36450.77,Z035,NaN,Z035,1.0
4,1001,0000020660,2018-04-05,2900453546,2018,1900018246,1,2018-03-26,2018-03-26,USD,032618TRAV,KR,H,2866.93,2866.93,0005,NaN,0005,10.0

In [59]:
# Calculate the difference between enter and cleared
joinDF['CLEAR_DAYS'] = joinDF['DAY_DOC_ENTERED'] - joinDF['DOCUMENT_DATE']

In [61]:
# Convert timedelta object to integer
joinDF['CLEAR_DAYS_INT'] = joinDF['CLEAR_DAYS'].dt.days

In [63]:
# Calculate difference between actual payment lag and vendor expectations
joinDF['CLEAR_DAYS_VENDOR_TERM_DIFF'] = joinDF['PAYMENT_TERM'] - joinDF['CLEAR_DAYS_INT']

In [68]:
# Create indicator for whether the term was successfully met or not
joinDF['MET_TERMS'] = ((joinDF['CLEAR_DAYS_VENDOR_TERM_DIFF'] >= 0))

In [71]:
# Write out the result to CSV
joinDF.to_csv(r'./../output/transaction_level/A30_Transaction_Base.csv', index=False)